from .auto_tagger import main  # noqa F401
from .create_relations import main  # noqa F401
from .create_tags import main  # noqa F401
from .delete_posts import main  # noqa F401
from .import_from_booru import main  # noqa F401
from .import_from_twitter import main  # noqa F401
from .import_from_url import main  # noqa F401
from .reset_posts import main  # noqa F401
from .tag_posts import main  # noqa F401
from .upload_media import main  # noqa F401
